os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
install:
  - git clone https://github.com/flutter/flutter.git -b stable
script:
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
notifications:
  email: false