name: chat_app_front
description: Chat App project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  email_validator: ^1.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.7+1
  http: ^0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lang/en.json
    - lang/pl.json